### ISSUE TITLE
Named outlets are not working with route resolve

### ISSUE THREAD

**Issue by balangovindaraj** [onehungrymind/ng2-named-router-outlets#4]
I have tried the same example with resolve back end API call. The first named outlet works the next one doesn't work. Any idea why it is not working with route-resolve !

**Comment by jdgarvey** [comment]
Hey @balangovindaraj 
Could you create a [plunk](https://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=preview) that demonstrates the error you are getting?
