### ISSUE TITLE
During instaling (npm i) get error    fatal: reference is not a tree: 7e55907cd54a2e91b96d25a660acc6a2a6453f54

### ISSUE THREAD

**Issue by vadimneta** [onehungrymind/ng2-named-router-outlets#5]
During instaling (npm i) 

 i get error 
   fatal: reference is not a tree: 7e55907cd54a2e91b96d25a660acc6a2a6453f54
please help
thanks

**Comment by jdgarvey** [comment]
Hi @vadimneta 
Can you create a [gist](https://gist.github.com/) of the full stack trace of the error and post the link here?
