### ISSUE TITLE
not found image 404 errors and material requirements

### ISSUE THREAD

**Issue by 4by4rus** [onehungrymind/ng2-named-router-outlets#7]
Hi
  I'm unable to reach the pictures and it just comes up with a black box icon. In the cosole I get the below message when the browser tries to load the images -

16:29:45.731 pele.jpg:1 GET http://localhost:4200/portfolio/players/assets/pele.jpg 404 (Not Found)
16:29:45.732 maradona.jpg:1 GET http://localhost:4200/portfolio/players/assets/maradona.jpg 404 (Not Found)
16:29:45.734 buffon.jpg:1 GET http://localhost:4200/portfolio/players/assets/buffon.jpg 404 (Not Found)
16:29:45.743 lothar.jpg:1 GET http://localhost:4200/portfolio/players/assets/lothar.jpg 404 (Not Found)
16:29:45.746 anotonio.jpg:1 GET http://localhost:4200/portfolio/players/assets/anotonio.jpg 404 (Not Found)

I dont have materials installed. Do I need it for the router outlets to work. I removed all scaffolding and into a new project, so I'm doing with the bare minimum. please see my env below. Am I missing something.
my url loads correctly - http://localhost:4200/portfolio/players/(list:playersList//bio:none)

and on the right side, I get please select a player, no player selected.
thanks

this is my env.
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.4.2
node: 6.11.3
os: win32 x64
@angular/animations: 4.3.1
@angular/common: 4.3.1
@angular/compiler: 4.3.1
@angular/core: 4.3.1
@angular/forms: 4.3.1
@angular/http: 4.3.1
@angular/platform-browser: 4.3.1
@angular/platform-browser-dynamic: 4.3.1
@angular/router: 4.3.1
@angular/cli: 1.4.2
@angular/compiler-cli: 4.3.1
@angular/language-service: 4.3.1
typescript: 2.3.3

**Comment by 4by4rus** [comment]
oops. not sure why the dependencies didnt come up on git
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.4.2
node: 6.11.3
os: win32 x64
@angular/animations: 4.3.1
@angular/common: 4.3.1
@angular/compiler: 4.3.1
@angular/core: 4.3.1
@angular/forms: 4.3.1
@angular/http: 4.3.1
@angular/platform-browser: 4.3.1
@angular/platform-browser-dynamic: 4.3.1
@angular/router: 4.3.1
@angular/cli: 1.4.2
@angular/compiler-cli: 4.3.1
@angular/language-service: 4.3.1
typescript: 2.3.3

**Comment by 4by4rus** [comment]
_                 ____ _     ___-->




















<!--typescript: 2.3.3

**Comment by 4by4rus** [comment]
oops. not sure why it did not like the @ above. repasting dependencies without @
angular/cli: 1.4.2
"node: 6.11.3
"os: win32 x64
"angular/animations: 4.3.1
angular/common: 4.3.1
angular/compiler: 4.3.1
angular/core: 4.3.1
angular/forms: 4.3.1
angular/http: 4.3.1
angular/platform-browser: 4.3.1
angular/platform-browser-dynamic: 4.3.1
angular/router: 4.3.1
angular/cli: 1.4.2
angular/compiler-cli: 4.3.1
angular/language-service: 4.3.1
typescript: 2.3.3

**Comment by jdgarvey** [comment]
Hey @4by4rus,
The image URLs should not have the actual route in them, it should just be `localhost:4200/assets/<image>.<ext>`. I would definitely make sure to install Angular Material. Although routing is obviously not a part of Angular Material, something could be breaking because of Material not being present, and then that messes up the rest of your app.

I would pull the latest from master, we just updated all dependencies to latest. Let us know if you still have issues. Thanks!
